language: node_js

install:
  - "npm install"
  - "tsc --version"
  - "ts-node --version"
  - "npm run install-packages"

script:
  - "npm run build"

after_success:
  - "npm run coverage"
  - "npm run coverage-report"
